apiVersion: v1
data:
  index.html: |
    hola mundo desde JuanJooo
kind: ConfigMap
metadata:
  name: web-assets
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      run: web
  strategy: {}
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: bitnami/nginx:1.14.0
        name: web
        resources: {}
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/html
          name: assets-vol
      volumes:
      - configMap:
          name: web-assets
        name: assets-vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    run: web
  annotations:
    nginx.ingress.kubernetes.io/lua-resty-waf: "active"
    nginx.ingress.kubernetes.io/rewrite-target: /
#    certmanager.k8s.io/acme-challenge-type: http01
#    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  name: web
spec:
  rules:
  - host: jjo-web.kube.um.edu.ar
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 8080
#  tls:
#  - hosts:
#    - <USER>.kube.um.edu.ar
#    secretName: web-cert
